---
- hosts: myservers
  task:
  - name: Obtener el/los archivo(s) de a el/los nodo(s) remoto(s)
    fetch:
       src: /home/arqsis/UEES/Hector/pruebaTrans.txt
       dest: /home/centos/Documentos/
       flat: yes
- hosts: myservers2
  task:
  - name: Copiar el archivo del/los nodo(s) remoto(s)
    copy:
      src: /home/centos/Documentos/
      dest: /home/oracle/UEES/AARIAS/HJIMENEZ/
      mode: preserve