---
- hosts: myservers
  tasks:
  - name: Obtener el/los archivo(s) de a el/los nodo(s) remoto(s)
    fetch:
       src: /home/centos/files/ctas_clientes.txt
       dest: /home/centos/Documentos/
       flat: yes