---
- hosts: myservers
  tasks:
  - name: Obtener el/los archivo(s) de a el/los nodo(s) remoto(s)
    fetch:
       src: /home/arqsis/UEES/Hector/pruebaTrans.txt
       dest: /home/centos/Documentos/
       flat: yes